spring:
  application:
    name: DistroTasker

  datasource:
    url: jdbc:postgresql://localhost:5432/distrotasker
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update  #DDL is data definition language - ie. tables are autocreated based on java entities
    show-sql: false     #hibernate will generate sql for the ddl, and also print to console
    properties:
      hibernate:
        format_sql: true #Formats SQL logs to be readable/verbose

server:
  port: 8080

logging:
  level:
    kapur: DEBUG

#rate-limiter config
distrotasker:
  rate-limiter:
    capacity: 10            #max tokens
    refill-interval-ms: 5000  #tokens refill every 5 seconds (10reqs/5s != 2reqs/sec)
  retry:
    max-retries: 3          #marks FAILED after
    base-delay-ms: 1000     #exponential backoff (2s, 4s, 8s)